// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

import { OrderBy, UserRole } from '@/config/consts';
import { RequestParams } from '@/lib/api-client';

export type BaseEntity = {
  id: string;
  createdAt: number;
};

export type Entity<T> = {
  [K in keyof T]: T[K];
} & BaseEntity;

export interface BaseSearch extends RequestParams {
  perPage: number,
  currentPage: number,
  order: string,
  orderBy: OrderBy,
};

export type User = Entity<{
  id: string;
  name: string;
  email: string;
  role: UserRole;
  image: string;
}>;

export type Post = Entity<{
  id?: string;
  title: string;
  body: string;
  authorId: string;
  author?: User;
  public: boolean;
}>;
